env: dev
namespace: mp-dev
image:
  repository: nginxdemos/hello
  tag: latest
replicaCount: 2
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi
containerPort: 80
